### ISSUE TITLE
Platform Build Setup

### ISSUE THREAD

**Issue by meenalsar008** [meenalsar008/SoftwareEngineeringCSYE7230#1]
### **EPIC**

Building the platform for the application where Admin with Client integration and Backend Server creation. Handling the primary tasks where we build the server for backend and create the initial project stages splitter in the TASKS. The Admin can Enable the sellers to add their components to the store dashboards and users and can add the medicine and store the e-store components with payment API and Google Location API integration.

### **STORY**

- [x] Task 1: BACKEND creation with Node and Express
- [x] Task 2: Admin creation with React
- [x] Task 3: Testing the URL handling with NODE-Express 
- [x] Task 4: Creating ADMIN protocols with CRUD  
- [x] Task 5: USER dash boarding UI implementation 
- [x] Task 6: Testing Data to produce and consume with User and Admin Client structure with DB

**Comment by SankalpRaptorAwasthi** [comment]
task 1 is completed in the phase 1 Epic duration

**Comment by yash-sah** [comment]
I will be taking up the Task 2

**Comment by meenalsar008** [comment]
Sequence of the website has been decided

**Comment by meenalsar008** [comment]
Closed
