### ISSUE TITLE
Phase 1 Production

### ISSUE THREAD

**Issue by SankalpRaptorAwasthi** [meenalsar008/SoftwareEngineeringCSYE7230#6]
# EPIC : PHASE 1 PRODUCTION
Setting up the server NodeJS backend with the client and Admin server. Monolith approach so gone with the development of 3 servers running parallelly for the projected build. 

# STORY

Server creation with route setting and react component integration for the phase 1 tasks 

# 1. Creating the Backend Server up
- [x] Set NodeJS Package
- [x] Set Express framework in
- [x] enable port 3000 route
- [x] work with the sign in routes
- [x] set route for dashboard route
- [x] set route for get and post data for Authentication

# 2. Creating the Admin Server up
- [x] Set React Package build project
- [x] Set Express framework in
- [x] enable port 4000 route
- [x] work with the sign in routes for admin 
- [x] setup a admin in DB for CRUD testing
- [x] enable dashboard route

# 3. Creating the Client Server up
- [x] Set React Package build project
- [x] Set Express framework in
- [x] enable port 8000 route
- [x] work with the sign in routes for users
- [x] link local MongoDB
- [x] fetch()for get and post data

**Comment by meenalsar008** [comment]
Done
